### ISSUE TITLE
Unable to install local plugins using Paq

### ISSUE THREAD

**Issue by Ttibsi** [savq/paq-nvim#104]
**Describe the bug**
Paq is unable to install a plugin held locally for testing purposes (IE when trying to write your own plugin). Instead, when adding the below to the init.lua file, the following error comes up when loading any nvim instance: 

```
Error detected while processing /home/auri/.config/nvim/init.lua:
 Paq: Failed to parse /dir/to/plugin
Press ENTER or type command to continue
```

**To Reproduce**
```lua
require "paq"{
    /dir/to/plugin";
}
```
where the plugin directory looks like this:
```
plugin
├── LICENSE
├── README.md
└── plugin
    └── init.lua
```

**Expected behavior**

**Environment:**
```
❯ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
❯ git --version
git version 2.25.1
```

- OS: Ubuntu 20.04 LTS

**Comment by savq** [comment]
Hi @Ttibsi

Paq doesn't support local plugins because it isn't really necessary. You can add a local plugin to your config by appending it to your runtime path:
```lua
vim.opt.runtimepath:append '~/path/to/your/plugin'  -- Use an absolute path
```
That's still a line of code, and it's (hopefully) more explicit than using Paq.

See `:h paq-misc`.
