### ISSUE TITLE
nvim 0.8: several packages fail to install

### ISSUE THREAD

**Issue by alxndr** [savq/paq-nvim#110]
**Describe the bug**

Using `:PaqInstall` on Neovim 0.8, several packages fail to install which worked in 0.7.0:

```
 Paq: [2/45] Failed to install vim-repeat
 Paq: [2/45] Failed to install blamer.nvim
Press ENTER or type command to continue
 Paq: [2/45] Failed to install vim-sexp
Press ENTER or type command to continue
 Paq: [2/45] Failed to install vim-sexp-mappings-for-regular-people
Press ENTER or type command to continue
 Paq: [2/45] Failed to install syntax-tree-surfer
Press ENTER or type command to continue
 Paq: [6/45] Failed to install trouble.nvim
Press ENTER or type command to continue
 Paq: [7/45] Failed to install nvim-treesitter-refactor
Press ENTER or type command to continue
 Paq: [7/45] Failed to install mini.nvim
Press ENTER or type command to continue
 Paq: sync complete. 0 ok; 8 errors; 37 no-ops
Press ENTER or type command to continue
```

**To Reproduce**

Install Neovim 0.8.0-dev, use [my config](https://github.com/alxndr/dotfiles/tree/af4910e/nvim), install Paq packages with `:PaqInstall`

**Expected behavior**

Packages install successfully as on 0.7.

**Environment:**
- `nvim --version`: NVIM v0.8.0-dev+15-g2458584
- `git --version`: 2.6.4
- OS: macOS Catalina 10.15.7 (19H1824)

**Comment by saccarosium** [comment]
Hey @alxndr, do you still have this issue?

**Comment by saccarosium** [comment]
I will close this for now. If you still have the issue, I will reopen this.
