### ISSUE TITLE
Add enable/disable feature for plugins

### ISSUE THREAD

**Issue by naveenadi** [savq/paq-nvim#111]

**Comment by naveenadi** [comment]
There is any way that, I am able to disable some plugin or enable in paq.

**Comment by David-Else** [comment]
You could try commenting it out, then do PaqSync.

**Comment by yochem** [comment]
You could also use `opt=true` on all, and then have a list of packages you want to enable with:

```lua
vim.cmd[[
packadd package1
packadd package2
" packadd package3 # commented out to disable it
]]
```

**Comment by saccarosium** [comment]
This can be done with now by: put `opt = true` on the package, resource the file where you call paq, then call `:PaqSync` and then restart neovim.
