### ISSUE TITLE
Paq fails to update folke/tokyonight.nvim always

### ISSUE THREAD

**Issue by SuborbitalSentinel** [savq/paq-nvim#119]
**Describe the bug**
If folke/tokyonight.nvim is included in my list of packages and `:PaqUpdate` is called a message will appear stating: ` Paq: Failed to update tokyonight.nvim`

**To Reproduce**
1. Have `folke/tokyonight.nvim` in your list of packages
2. Call :PaqUpdate or :PaqSync

**Expected behavior**
The plugin to either update or report that it is up to date

**Environment:**
 - `nvim --version`: NVIM v0.7.2
- `git --version`: git version 2.37.1.windows.1
- OS: Windows 10

**Comment by ChaoticSentinel** [comment]
To add more details, I tested this on Linux and the problem does not seem to occur there.

**Comment by scowan1995** [comment]
I get this on my linux machine. 
NVIM v0.8.0-dev+476-g3a4fa22ba
git version 2.34.1
os: Ubuntu 22.04

I just call PaqSync and get:
 Paq: Nothing to remove                                                                                                                                                                                                                                 
 Paq: [0/29] Failed to update tokyonight.nvim                                                                                                                                                                                                           
 Paq: sync complete. 0 ok; 1 errors; 28 no-ops

**Comment by saccarosium** [comment]
I can't reproduce this. If still happens feel free to reopen the issue.
