### ISSUE TITLE
failed to run `cd` as post install hook

### ISSUE THREAD

**Issue by doongjohn** [savq/paq-nvim#120]
**Describe the bug**

`cd` produces this error
`Paq: Failed to spawn cd (ENOENT: no such file or directory)`

**To Reproduce**

```lua
  {
    'iamcco/markdown-preview.nvim',
    run = [[cd app]]
  };
```

**Expected behavior**

error should not occur

**Environment:**
 - `nvim --version`: 0.7.2
- `git --version`: 2.37.2
- OS: WSL2 (Void linux)

**Comment by savq** [comment]
The `run` option does not spawn a shell. It spawns the process directly using libuv (see [`:help luv`](https://neovim.io/doc/user/luvref.html)) in the directory of the plugin.

The solution suggested by Barrett is indeed the best alternative.
