### ISSUE TITLE
self-installing example

### ISSUE THREAD

**Issue by craigmac** [savq/paq-nvim#129]
In case this might be useful for others looking for a one-file [kickstart-style](https://github.com/nvim-lua/kickstart.nvim) setup, here's what I'm doing:

In `~/.config/nvim/init.lua`:

```lua
local path = vim.fn.stdpath('data') .. '/site/pack/paqs/start/paq-nvim'
local first_install = false

if vim.fn.glob(path) == "" then
  first_install = true
  vim.fn.system({ 'git', 'clone', 'https://github.com/savq/paq-nvim', path })
  vim.cmd.packadd('paq-nvim')
end

local packages = {
  'savq/paq-nvim',
  -- your packages
}

local paq = require('paq')
if first_install then print('Paq: first install, plugins being installed, if prompted hit Enter to continue.') end
paq(packages)
paq.install()

vim.api.nvim_create_autocmd('BufWritePost', {
  command = 'silent PaqClean | silent PaqInstall',
  group = vim.api.nvim_create_augroup('Paq', { clear = true }),
  pattern = vim.fn.expand('$MYVIMRC'),
})
```

Don't know if it's worth adding to the docs or not, but just thought I'd add it here in case someone is looking how to do it. Feel free to point out mistakes I might have made in the above! Thanks.

**Comment by craigmac** [comment]
Benefit of this way, is there's no restart Neovim required. I can wipe out my packpath start nvim with this, it installs everything and I can work right away.

**Comment by savq** [comment]
Maybe we could edit `:h paq-bootstrapping` to show both the script-ish and the config-ish ways to install paq and plugins.

On that note, [I should make my own kickstart.nvim](https://i.kym-cdn.com/entries/icons/original/000/011/656/sophiscated_cat.PNG)
