### ISSUE TITLE
Feature Request: SSH

### ISSUE THREAD

**Issue by barrett-ruth** [savq/paq-nvim#133]
It seems like SSH is the new standard (or, at least, recommended practice) for interacting with github repos.

What are your thoughts on using SSH urls instead of HTTPS? Or possibility of adding a `use_ssh` option to the paq config?

**Comment by savq** [comment]
> What are your thoughts on using SSH urls instead of HTTPS?

[I 'm neutral.](https://www.youtube.com/watch?v=ussCHoQttyQ)

> Or possibility of adding a use_ssh option to the paq config?

Paq should probably have a way to set the default URL format, so a user can choose between ssh and https, but also use forges other than github as a default.

**Comment by savq** [comment]
Closed by #134
