### ISSUE TITLE
`opt = true` not respected

### ISSUE THREAD

**Issue by beardedsakimonkey** [savq/paq-nvim#135]
**Describe the bug**
In plugin configs, passing `{opt=true}` no longer installs plugins to the `opt/` directory

**To Reproduce**
```lua
require'paq'{{'mbbill/undotree', opt=true}}
```

**Expected behavior**
After running `:PaqInstall`, there should exist a directory `~/.local/share/nvim/site/pack/paqs/opt/undotree`.  Instead, it's in `~/.local/share/nvim/site/pack/paqs/start/undotree`.

**Environment:**
 - `nvim --version`: 0.9

I believe this regressed in https://github.com/savq/paq-nvim/commit/07407b2fcda4d049b2bdd58d658bfc59e1e5aa22

I think the root cause is that this line
https://github.com/savq/paq-nvim/blob/07407b2fcda4d049b2bdd58d658bfc59e1e5aa22/lua/paq.lua#L280
will result in `opt` always being `false` if `cfg.opt` is false.
Perhaps it should be something like this instead:
```lua
    local opt
    if cfg.opt then
        opt = args.opt == true or args.opt == nil
    else
        opt = args.opt
    end

```

cc @saccarosium

**Comment by saccarosium** [comment]
PR opened. Sorry for not having tested better the logic.

**Comment by saccarosium** [comment]
Should be resolved now
