### ISSUE TITLE
Synchronous plugins installation

### ISSUE THREAD

**Issue by sakhnik** [savq/paq-nvim#146]
Hello, would it be possible to add some argument to `:PaqInstall` for synchronous execution? It'd allow automated deployment of neovim from the command line like `nvim +PaqInstall +quit`.

**Comment by savq** [comment]
Neovim doesn't have synchronous installation, but it has user autocommands that run after an install or update. See `:help paq-autocommands`.

There's also a small guide that explains how to write a script you can call in headless mode. See `:help paq-bootstrapping`.
