### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by PhilT** [savq/paq-nvim#15]
I just installed some packages with paq-nvim on Windows. It seems to work so far. Could probably could do to add the following to the README for Windows users. Happy to open a PR if that's preferable.

### Windows
```
git clone https://github.com/savq/paq-nvim.git "$env:LOCALAPPDATA\nvim-data\site\pack\paqs\opt\paq-nvim"
```

**Comment by savq** [comment]
That's good to hear. I'll add it to the readme.

I'll also add a disclaimer indicating that there's currently no testing being done on Windows. libuv should take care of all the OS-dependent magic, but you never know…
