### ISSUE TITLE
cur_hash is always euqal prev_hash, even if a package got updated, leaving the log file empty

### ISSUE THREAD

**Issue by potamides** [savq/paq-nvim#160]
**Describe the bug**
paq-nvim seems to have functionality to log commit messages of updated packages, but nothing appears in my log file, even when a newer version of a package got pulled. Upon inspection, it seems like the retrieved `cur_hash` after pulling a package ([here](https://github.com/savq/paq-nvim/blob/07eb567dbb70044cabc622900b2bf755f7aecb99/lua/paq.lua#L309) in the code) seems to be always equal to the `prev_hash`. Indeed, if I manually set `cur_hash` to the new hash, then the update notes appear in the log as expected.

**To Reproduce**
Install some packages with paq-nvim, wait until there are new commits and then try to update.

**Expected behavior**
The commit messages of the pulled commits should appear in the log file.

**Environment:**
 - `nvim --version`: v0.9.2
- `git --version`: 2.42.0
- OS: Arch Linux

**Comment by potamides** [comment]
Seems like my problem got introduced with [this](https://github.com/savq/paq-nvim/commit/2a7715861540fa6b18f379840120abd97c711d7e#diff-fe7438a5be2e259d60b3b450a6cbd0e5c632ee00470f9666eee75307b0668afbL165-R229) change. If I revert that, everything is working as expected.

**Comment by saccarosium** [comment]
Hi, @potamides. Sorry I took so long to respond. Could you please make a PR? If not I will make time to fix this.

**Comment by potamides** [comment]
No worries! I will create a PR for that.
