### ISSUE TITLE
paq function sends 'parse' as argument - not in table so it fails

### ISSUE THREAD

**Issue by ZNielsen** [savq/paq-nvim#17]
`output_result('parse', args[1])`
'parse' is not in ops, so paq fails when trying to access a nil value

error text:
`Error executing lua .../share/nvim/site/pack/paqs/opt/paq-nvim/lua/paq-nvim.lua:58: attempt to index local 'c' (a nil value)`

**Comment by savq** [comment]
Merged #18 a moment ago but forgot to close the issue. Again, thanks for noticing. I also added a test for this just in case.
