### ISSUE TITLE
How can i install plugins in a synchronous way.

### ISSUE THREAD

**Issue by 231tr0n** [savq/paq-nvim#170]
Hello and first of all thank you for this amazing neovim plugin manager. I wanted to know if there is any method like installSync or similar functionality of sort since everytime i add a new plugin, I end up with an error and my config wont load. Is there any way to prevent this from happening.

**Comment by saccarosium** [comment]
Can you provide the error that it gives you and the config where you call paq?

**Comment by 231tr0n** [comment]
![image](https://github.com/savq/paq-nvim/assets/56352048/b80bd8ca-a766-4831-aab8-53650e9ec412)
When ever I add a new plugin, in my case it is a colorscheme called cyberdream.nvim and reopen neovim this error popups up and once i press enter, then the plugin is installed. But the require function is called before the plugin is installed sync paq.install() method runs asynchronously I guess.
Also below is my config
https://github.com/231tr0n/config/blob/main/nvim/init.lua

**Comment by saccarosium** [comment]
Currently the best way to get this behavior in paq is using the setup option `opt` to set the default install directory to the opt directory (see `:h packages`) and then load the plugins using packadd.

I took the liberty to refactor your `bootstrap_paq` function, which is now the only function you need (you can remove `clone_paq` and `paq_path`)

```lua
local function bootstrap_paq(packages)
	local path = vim.fn.stdpath("data") .. "/site/pack/paqs/start/paq-nvim"
	if not vim.uv.fs_stat(path) then
        local url = "https://github.com/savq/paq-nvim.git"
		vim.fn.system({ "git", "clone", "--depth=1", url, path })
        vim.cmd.packadd("paq-nvim")
		vim.notify("Installing plugins")
	end
	local paq = require("paq"):setup({ opt = true })(packages)
    local to_install = paq.query("to_install")
    if not vim.tbl_isempty(to_install) then
        paq.install()
    end
    for _, p in pairs(packages) do
        if type(p) == "table" then
            p = p[1]
        end
        p = {vim.fs.basename(p)}
        vim.cmd.packadd({ args = p, bang = true })
    end
end
```

This should solve the problem.

**Comment by saccarosium** [comment]
The problem here is not that paq downloads packages asynchronously but rather that vim packages doesn't cope well with loading at runtime things from the start directory. Even if you force it with rtp. So for this reason the most manageble solution is to use the opt directory by default and then load the packages in bulk.
