### ISSUE TITLE
Unclear when cleaning has completed

### ISSUE THREAD

**Issue by PhilT** [savq/paq-nvim#19]
Comment out one plugin and to `PaqClean` message reads `Paq [1/28] removed`.

Either it needs to say `Paq [1/1] removed` or it needs to say when it's completed. Something like `Paq [1/28] removed. Operation completed.` Personally I prefer if it said `[1/1]`.

**Comment by PhilT** [comment]
Nice plugin by the way :)

**Comment by savq** [comment]
Yeah, that is still a bit weird. #2 fixed the same problem for installs and updates, but not for uninstalls. I think I 've a better idea on how it should work now. I'll try adding it today or monday.

**Comment by PhilT** [comment]
Cheers. Let me know if you'd like someone to test it.
