### ISSUE TITLE
Plugins still loaded even when commented out

### ISSUE THREAD

**Issue by PhilT** [savq/paq-nvim#20]
Sometimes when testing out different plugins it's useful to disable them without having to uninstall them (`PaqClean`).

If it's possible to actually check which plugins are listed in my `init.lua` and use that to load them instead of just load what's in the `pack/` directory I think that would be more clear for users as well as not having to redownload  when you want to re-enable the plugin.

**Comment by savq** [comment]
Well, that's because Paq doesn't actually do any of the loading. Neovim does. Listed plugins is telling Paq "track this" rather than a "use this".


Alternative solution:

When trying plugins, using the `opt` option will download them in `pack/paq/opt`, so they won't load on startup:

```lua
paq{'bob/foo', opt=true}
paq{'alice/bar', opt=true}

local current = 'foo'
vim.cmd('packadd ' .. current)
```

**Comment by PhilT** [comment]
VimPlug allows this functionality but okay.
