### ISSUE TITLE
Proper completed/errors messages for PaqInstall and PaqUpdate

### ISSUE THREAD

**Issue by kiuKisas** [savq/paq-nvim#33]
Currently,  `paq-nvim` doesn't show any errors if something wrong happen.
For example, with a wrong repo name (e.g: `paq 'neovim/nvim-lspconfg'`),  I had three differents behavior when trying other and other (until I figure it.. ^^' ):
-  seems to be stucks at the previous package
-  doesn't show anything
-  print  `Username for 'https://github.com':` at the top of my current window (and freeze neovim)

It can be a bit confusing.

Also, it could be great to habe a message at the end of installation/update saying something like '15 packages was installed/updated !'

Thank's for this plugin btw, really appreciate it in my new nvim config :]

**Comment by savq** [comment]
> Currently, paq-nvim doesn't show any errors if something wrong happen.

Yeah, Paq isn't very good in that aspect.

> print Username for 'https://github.com': at the top of my current window (and freeze neovim)

This has been a common issue, it's been mentioned before, but it's been hard for me to reproduce.

> message at the end of installation/update saying something like '15 packages was installed/updated

Paq does show the package count… Could you try deleting the directory where it's installed and reinstalling it again?

**Comment by savq** [comment]
I've added a troubleshooting section to the docs. Just the most basic things for now. I'll see what I can add in the future.

I also updated the prompt messages so that errors are properly highlighted (with `hl-Error` I assume). Remember you can always re-check the messages with the `:messages` ex-command.

**Comment by gammons** [comment]
@savq I noticed that you'll get a github prompt for a username when you try to install a package that doesn't exist.  In my case, I was trying to install `mhartington/formatter`.  However the repo is actually named `mhartington/formatter.nvim`.
