### ISSUE TITLE
packages dependencies

### ISSUE THREAD

**Issue by juantascon** [savq/paq-nvim#34]
good day,

is there a way to specify dependencies between packages, if not then what is the recommendation for that use case?

thank you

**Comment by toniz4** [comment]
I group my packages that depend on other packages, so once I want to remove that package, It will be easy to remove the other ones. Having added complexity to do that is unnecessary, package dependencies are rare in (n)vim, and it's easy to manage manually. In my opinion.

**Comment by savq** [comment]
Yeah, grouping packages or writing comments are ways to show dependencies.

I'm not really interested in adding a feature to specify dependencies.

[packer.nvim](https://github.com/wbthomason/packer.nvim/) does implement dependency declaration, you might want to look into that.

**Comment by savq** [comment]
I don't think there'll be further disscution on this issue. Closing for now.
