### ISSUE TITLE
Prompt for github credentials

### ISSUE THREAD

**Issue by boydkelly** [savq/paq-nvim#4]
Hi,  Was just wanting to try this out and followed the readme config.  I do have a long list of plugins, but it seems that paq must be prompting me for most/all of them as they fill the screen.   I'm not sure if its hanging or installing.   In any case not sure why since normally you don't need an account for an https download. I just put a sample of my init here.

`paq{'gvim-airline/vim-airline-themes', opt=true }    
paq{'lervag/vimtex', opt=true }       
paq{'boydkelly/vim-mutton', url = 'https://gitlab.com/boydkelly/vim-mutton' }   
paq 'gairblade/vim-rooter'    
paq 'gandymass/vim-matchup'    `

And the results of Paqinstall:

`or 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': 
`

**Comment by savq** [comment]
There's a typo in some of your packages. I think you accidentally wrote a g in visual block mode at the start of some of the repo names.

Other than that, I find it strange that github prompts for the username. Paq only clones and pulls repos, it doesn't push anything. The only reason why it'd prompt you is if you were cloning a private repo, but that's not the case here.

**Comment by savq** [comment]
Just today I received an email about the deprecation of password authentication
for GitHub. This might be related to that.

[Token authentication requirements for Git operations](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/)

[Token authentication requirements for API and Git operations](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/)

**Comment by crispgm** [comment]
> Just today I received an email about the deprecation of password authentication for GitHub. This might be related to that.
> 
> [Token authentication requirements for Git operations](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/)
> 
> [Token authentication requirements for API and Git operations](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/)

Should paq-nvim switch from https protocol to ssh instead to comply GitHub's policy?
