### ISSUE TITLE
:PaqInstall broken with recent update

### ISSUE THREAD

**Issue by npaulcarlson** [savq/paq-nvim#40]
I ran a `:PaqUpdate` today, and since have been unable to successfully run `:PaqInstall`. Error shown in screenshot reads:

> E5108: Error executing lua .../share/nvim/site/pack/paqs/opt/paq-nvim/lua/paq-nvim.lua:52: attempt to index upvalue 'ops' (a function value)

After reading through the code, I think it's related to the bodge here:
https://github.com/savq/paq-nvim/blob/e127a28765c383618b73e7a26a3d1c9f7a7dfa58/lua/paq-nvim.lua#L49

I would give fixing it myself a go, but I'm neither familiar with Neovim's Lua API nor particularly familiar with Lua itself.

**Comment by chiendo97** [comment]
I have the same issue.

**Comment by savq** [comment]
That's a typo. Sorry folks.

**Comment by savq** [comment]
Also, the typo happened because I'm moving Paq to a different declaration syntax meant to fix some reloading problems. I'll mantain compatibility with the old syntax probably until neovim 0.5 is released. In the mean time some of these hacky fixes will be around.

**Comment by npaulcarlson** [comment]
Would have fixed it myself had I known it were that simple. Thanks!
