### ISSUE TITLE
PaqInstall - paq-nvim.lua:82: bad argument #1 to 'open' 

### ISSUE THREAD

**Issue by zekus** [savq/paq-nvim#42]
Just installed and run `:PaqInstall` for the first time.

```
E5108: Error executing lua .../share/nvim/site/pack/paqs/opt/paq-nvim/lua/paq-nvim.lua:82: bad argument #1 to 'open' (number expected, got nil)
```

**Comment by zekus** [comment]
starting with a clean Neovim configuration works. closing.

**Comment by DanKGooGLy** [comment]
What did you do?

**Comment by DanKGooGLy** [comment]
Nevermind.

**Comment by bewakes** [comment]
In my case, this is still occuring when there is no directory `~/.cache/nvim`. This looks like a bug.
