### ISSUE TITLE
FYI: If using with 0.5 treesitter will break

### ISSUE THREAD

**Issue by johnf** [savq/paq-nvim#49]
The compat file seems to override vim variable and them vim.treesitter doesn't exist

**Comment by windwp** [comment]
https://github.com/savq/paq-nvim/commit/b2ce3e653b61b63da509267879b6b82909de49e6

that commit break vim.lsp and treesitter.

**Comment by AnthonyK213** [comment]
Same here. I preferred paq because it's simple and lightweight, but it is getting more like packer.nvim over time, however, buggy to use.

**Comment by elliottgreen** [comment]
I was able to recover functionality by commenting out the  "local vim = require("paq.compat")" line 
in .local/share/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua"

It looks like that is going to be dropped anyway since 0.5 is stable now.

**Comment by savq** [comment]
@windwp is correct. Using the previous commit works.

@elliottgreen I'm not removing `paq.compat` since I don't know how fast distros will upgrade.

Fixed by #50

**Comment by stvhuang** [comment]
@savq Maybe you can create a branch that requires neovim 0.5. And `paq.compat` can be removed in that branch.
