### ISSUE TITLE
Paq post-install hook 'run' failed

### ISSUE THREAD

**Issue by zpah** [savq/paq-nvim#56]
Command :PaqInstall failed on config:

    require 'paq' {
      {'junegunn/fzf', run = '/bin/true'};
    }

Error message:

    Error executing vim.schedule lua callback: ...-nvim/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua:54: bad argument #4 to 'format' (string expected, got nil)

Neovim 0.5.0
paq-nvim 0.9.2

**Comment by savq** [comment]
Hey @zpah,

I saw that this was a formatting issue, and that you already fixed it in your fork. If you want to you can make a PR and I'll merge it.

**Comment by zpah** [comment]
> Hey @zpah,
> 
> I saw that this was a formatting issue, and that you already fixed it in your fork. If you want to, you can make a PR and I'll merge it.

Sorry for the late response. There were several more errors in paq-nvim and i gave up the paq-nvim in favor of vim-plug.
