### ISSUE TITLE
Unable to install paq-nvim

### ISSUE THREAD

**Issue by paniash** [savq/paq-nvim#58]
Hi!

I'm currently using vim-plug and wanted a more minimal package manager and found your plugin. Going through the installation instructions, I cloned the repo to `~/.local/share/nvim` and subsequently wrote in my `init.vim` (as an example):

```vim
lua <<EOF
require 'paq-nvim' {
    'paq-nvim';
    {'neoclide/coc.nvim', branch='release'};
}
EOF
```

However, on running `:PaqInstall`, I get the error message as `Not an editor command: PaqInstall`.

Not sure what I'm doing wrong.

**Comment by henriquehbr** [comment]
@paniash quoted from [this](https://stackoverflow.com/a/50122211/9182121) question on StackOverflow:

> Both Vim 8.0 and Neovim have their own built-in package manager.
>
> In VIm 8.0, create the following directories:
>
> - `~/.vim/pack/*/start` (where `*` may be any name e.g. `~/.vim/pack/jimmy/start`): Clone your required > plugin into the start directory just as you would if you were installing it for Pathogen. You need > nothing more and no commands in your `.vimrc` file.
> - `~/.vim/pack/*/opt` (e.g. `~/.vim/pack/jimmy/opt`) for plugins that only need to be loaded as required. > For colours, add a directory to the opt directory and then your colours e.g. > `~/.vim/pack/jimmy/opt/mycolors/colors/dracula.vim`.
>
> In **Neovim**, the directory structure follows the freedesktop's XDG Base Directory Specification. Your configuration file is in `~/.config/nvim/init.vim`, but your plugins go into:
>
> - `~/.local/share/nvim/site/pack/*/start`
>
> See `:h packages` (VIm 8.0 and Neovim) for more information.
