### ISSUE TITLE
Git Submodules

### ISSUE THREAD

**Issue by AdrienLeGuillou** [savq/paq-nvim#6]
Hi !

Is there a way to update git submodules during installation and on updates?

I ran into an issue whith https://github.com/nvim-telescope/telescope-fzy-native.nvim. I work my way around it by going into the ".../paqs/start/telescope-fzy-native.nvim" folder and running `git submodule update --init --recursive` but it would be great to have it automatically done.

Thanks for all your work !

**Comment by savq** [comment]
Could you try creating a hook for that operation?
```lua
paq{'nvim-telescope/telescope-fzy-native.nvim', hook='git submodule update --init --recursive' }
```

**Comment by AdrienLeGuillou** [comment]
It works like a charm, I just tested that on a fresh neovim install. I did not read the documentation thoroughly enough and miss the "**in the directory of the package**." part of hook.

Thanks a lot for taking the time
