### ISSUE TITLE
Support for a user autocmd?

### ISSUE THREAD

**Issue by fsouza** [savq/paq-nvim#71]
paq-nvim is almost everything I've been looking for: an easy to use, fast and simple package manager. I was wondering if you'd take a pull request that adds a custom user autocmd that's invoked at the end of operations?

Basically thinking of bootstrap here: if I wanted invoke something like paq:sync() and then exit neovim once it's done. I'd need a way to exist for the async processes to finish before quitting.

**Comment by savq** [comment]
@fsouza I finally added this feature! The autocommands are listed in `:help paq-autocommands`, and I also added a section on bootstrapping to the docs (although it's somewhat bare-bones at the moment).
