### ISSUE TITLE
Package installs, but doesn't load anymore when restarting neovim

### ISSUE THREAD

**Issue by Cloudperry** [savq/paq-nvim#74]
Adding [this](https://github.com/alaviss/nim.nvim) plugin to paq installs it and it loads normally after install. After restarting neovim the plugin doesn't load anymore. 

The easiest way of testing this is to install the plugin and type nim in command mode and then press tab for command completions. Right after plugin install there are multiple commands provided by the plugin, but after restarting neovim and looking for commands that start with nim, there are none.  

For now I worked around this by installing all my other plugins with paq and installing this one plugin with vim-plug. Its weird that all the other plugins I have work with paq, but this one doesn't.

**Comment by savq** [comment]
I tried the plugin and the error I got was:
```
nim.nvim: nimsuggest (nimsuggest) cannot be executed: Vim(let):E475: Invalid value for argument cmd: 'nimsuggest' is not executable
```

`nimsuggest` doesn't appear in the requirements in the readme…

> Right after plugin install there are multiple commands provided by the plugin, but after restarting neovim and looking for commands that start with nim, there are none.

When I open a Nim file, I get three commands: `NimDocOf`, `NimReferences` and `NimTypeOf`. The first two don't seem to do anything, and the third fails with:
```
nim.nvim: nimsuggest (nimsuggest) cannot be executed: Vim(let):E475: Invalid value for argument cmd: 'nimsuggest' is not executable
Error detected while processing function nim#suggest#def#ShowType[5]..nim#suggest#utils#Query:
line   16:
E716: Key not present in Dictionary: "query"
```

I'll take another look if alaviss/nim.nvim#44 is resolved.

**Comment by Cloudperry** [comment]
Thanks for taking a look at this issue. Idk what has changed since then but I don't have this bug anymore. Also nimsuggest isn't listed as a requirement in that plugin because the plugin is meant for Nim developers and assumes you have installed the Nim programming language (and the tools that come with it).
