### ISSUE TITLE
failed to run post update hook (string of shell command)

### ISSUE THREAD

**Issue by uga-rosa** [savq/paq-nvim#76]
```lua
require("paq")({
  {"junegunn/fzf", run = "./install --all"}
})
```

output message
`Paq [] failed to run hook for fzf`

**Comment by franmagneto** [comment]
@uga-rosa how did you solve it? I'm having the same problem

**Comment by uga-rosa** [comment]
@franmagneto I'm sorry. I don't know how to solve this problem since I gave up using this plugin.

**Comment by franmagneto** [comment]
@uga-rosa thank you!
