### ISSUE TITLE
How do you load config file?

### ISSUE THREAD

**Issue by medwatt** [savq/paq-nvim#81]
I currently have this in my init.lua. As long as the plugin is not installed, I get an error on startup telling me the plugin is not installed. If I install the plugin, then the code works fine and runs the config file. Let's say I delete my plugins folder and want to reinstall everything from scratch. Then, I will have to all the lines with the `run` option, install the plugins, and reinsert the line back. Surely, there has to be a better way to do this.

```lua
require "paq" {
    {'folke/which-key.nvim', run = require('main.plugin_config.which-key_config')}
}
```

**Comment by Bowuigi** [comment]
Replace whatever is on the run with the following:

```lua
function() if pcall(require, "[plugin]") then require("main.plugin_config.[plugin]_config")() end end
```

Here is a function to generate all of this automagically:

```lua
function PConfig(plugin)
    return function() if pcall(require, plugin) then require("main.plugin_config."..plugin.."_config")() end end
end
```

So you could just do, for example:

```lua
require("paq") {
    {"folke/which-key.nvim", run = PConfig("which-key")}
}
```

**Comment by RayZ0rr** [comment]
> Here is a function to generate all of this automagically:

This looks like a neat little alternative to `config` in [packer](https://github.com/wbthomason/packer.nvim). @savq Could you add this to README or the wiki ?

**Comment by megalithic** [comment]
Any thoughts on if this is still _the way_ to achieve such packer-esque behaviour for collocating plugin configs? Since `run` only seems to run post-install; how does this work to actively do the config require sourcing each time you load nvim? @Bowuigi / @savq -- thank you for this amazing plugin!

**Comment by RayZ0rr** [comment]
I don't think this fits paq's minimalistic nature. One solution to this problem is to put plugins and configurations in a table and then load them separately. Eg from my own config:
```lua
local plugAndConfig = {

  -- Each element should be like this:
  -- {'plugin/name','config name used in require'}
  -- config name is optional

  -- Let Paq (plugin manager) manage itself
  {"savq/paq-nvim"},

  --------------------------------------------------
  -- GENERAL
  --------------------------------------------------

  -- fzf ----------------------------------------
  {'vijaymarupudi/nvim-fzf'},
  {'kyazdani42/nvim-web-devicons'},
  {'ibhagwan/fzf-lua','plugins/general/fzf-lua'},
  -- Undo history ------------------------------
  {'mbbill/undotree',"plugins/general/undotree"},
  -- Build, Run tasks (commands) in background asynchronously
  {'skywind3000/asyncrun.vim','plugins/general/asyncRunTasks'},
  -- File Browser ------------------------------
  {'is0n/fm-nvim','plugins/general/fm-nvim'},
  -- Autocompletion plugin ---------------------
  {'hrsh7th/cmp-nvim-lsp'},
  {'hrsh7th/cmp-buffer'},
  {'hrsh7th/cmp-path'},
  {'hrsh7th/nvim-cmp','plugins/general/nvim-cmp'},
  -- Other plugins and configs
}

local plugList = {}
local configList = {}

for idx, items in pairs(plugAndConfig) do
  plugList[idx] = items[1]
  if items[2] then
    table.insert(configList,items[2]);
  end
end

-- don't throw any error on first use by packer
local ok, paq = pcall(require, "paq")
if not ok then return end

require("paq")(plugList)

-- Load configs
for idx, config in pairs(configList) do
  require(config)
end
```
