### ISSUE TITLE
Add support for proxy settings

### ISSUE THREAD

**Issue by mbkroese** [savq/paq-nvim#82]
In the function `call_proc`, the second argument to `uv.spawn` gets an `env` parameter.
If the user has `http_proxy` and/or `https_proxy` set the command called in `uv.spawn` might fail if that setting is not passed down.

So, I think there could be two easy fixes for this:

1. Automatically set the `http(s)_proxy` as `env` parameter when the user has those bash variables set.
2. Allow users to specify a `http(s)_proxy`.

I had issues cloning plugins because this could not be set. However, setting the proxy settings in `env` solved it.

**Comment by savq** [comment]
Related to #77

**Comment by savq** [comment]
Paq now makes a copy of the current environment so that doesn't happen. should be ok now.
