### ISSUE TITLE
Paq uses the wrong case for autocommands

### ISSUE THREAD

**Issue by keithhub** [savq/paq-nvim#92]
**Describe the bug**
The help shows standard PascalCase names for the user autocommands but the code is actually using `PaqDone` plus the operation in lowercase. For example `PaqDoneinstall` is used instead of `PaqDoneInstall`. Although the nvim help implies the names should be treated case-insensitively, an autocommand for `PaqDoneInstall` fails to run.

**To Reproduce**
Run the example as given in `:help paq-bootstrapping`. The `quit` is never executed and nvim has to be manually killed.

**Expected behavior**
The `nvim --headless ...` command should exit and return to the shell after packages have been installed.

**Environment:**
 - `nvim --version`:
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `git --version`:
```
git version 2.34.1
```

- OS:
```
Arch Linux
Linux 5.15.8-arch1-1 #1 SMP PREEMPT Tue, 14 Dec 2021 12:28:02 +0000 x86_64 unknown GNU/Linux
```

**Comment by savq** [comment]
Weird. I haven't had issues with the lower-case autocmd and—as you mentioned—the nvim docs say that the event names are case-insensitive.

Still, better to be sure than to hope it works.
