### ISSUE TITLE
Outdated information on the comparison section of the wiki

### ISSUE THREAD

**Issue by henriquehbr** [savq/paq-nvim#95]
Currently, there's a outdated information on the wiki, more specifically, on the paq-nvim x Packer comparison section:

> Another—more concrete—difference is that Paq works with Neovim 0.4 (stable), while Packer requires Neovim 0.5.

I was checking through the commit log, and seems to be a fairly recent change made (at the time of writing this) a little less than a month ago (59d768fc9e09eab31ec9ff9e8461671ce23670b0), i'm not sure how can i edit the wiki, otherwise i would've made such change already

**Comment by henriquehbr** [comment]
My apologies, just noticed now that i accidentally tagged this issue as a `bug`, should've opened a blank one instead

**Comment by savq** [comment]
Fixed. Thanks for letting me know, and sorry for the delay.
