### ISSUE TITLE
PaqClean doesn't remove plugin from filesystem

### ISSUE THREAD

**Issue by abenz1267** [savq/paq-nvim#96]
Hi, doing `:PaqClean` doesn't remove a plugin, despite not being added anywhere in the config and `:PaqList` not showing it. Plugin in question is https://github.com/folke/which-key.nvim

You can checkout my config at https://github.com/abenz1267/nvim. I've added which-key exactly the way i added the others.

Any idea?

**Comment by savq** [comment]
I think #94 fixes this. Can you check again?

**Comment by abenz1267** [comment]
Yep, just tested. Seems to be fixed!
